version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/issue-tracker

permissions:
  - object: /home/ubuntu/issue-tracker
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 60
      runas: root